services:
  zookeeper:
    container_name: zookeeper
    image: ${ZOOKEEPER_IMAGE}
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    networks:
      - local-dev-net
    restart: unless-stopped
    deploy:
      replicas: ${BUILD_ZOOKEEPER-0}

  kafka:
    container_name: kafka
    image: ${KAFKA_IMAGE}
    platform: ${DEV_PLATFORM}
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_LISTENERS: INSIDE://0.0.0.0:${KAFKA_PORT},OUTSIDE://0.0.0.0:${KAFKA_EXTERNAL_PORT}
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:${KAFKA_PORT},OUTSIDE://localhost:${KAFKA_EXTERNAL_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"  # Allows PLAINTEXT communication
    ports:
      - "${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}"
    expose:
      - ${KAFKA_PORT}
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - local-dev-net
    depends_on:
      - zookeeper
    restart: unless-stopped
    deploy:
      replicas: ${BUILD_KAFKA-0}

  mysql:
    container_name: mysql
    image: ${MYSQL_IMAGE}
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - local-dev-net
    restart: unless-stopped
    deploy:
      replicas: ${BUILD_MYSQL-0}

  postgres:
    container_name: postgres
    image: ${POSTGRES_IMAGE}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local-dev-net
    restart: unless-stopped
    deploy:
      replicas: ${BUILD_POSTGRES-0}

  redis:
    container_name: redis
    image: ${REDIS_IMAGE}
    ports:
      - "${REDIS_EXTERNAL_PORT}:${REDIS_PORT}"
    networks:
      - local-dev-net
    volumes:
      - redis_data:/data
    restart: unless-stopped
    deploy:
      replicas: ${BUILD_REDIS-0}

  akhq:
    container_name: akhq
    image: ${AKHQ_IMAGE}
    platform: ${DEV_PLATFORM}
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            default:
              properties:
                bootstrap.servers: "kafka:${KAFKA_PORT}"
    ports:
      - "${AKHQ_EXTERNAL_PORT}:${AKHQ_PORT}"
    networks:
      - local-dev-net
    restart: unless-stopped
    deploy:
      replicas: ${BUILD_AKHQ-0}

  prometheus:
    container_name: prometheus
    image: ${PROMETHEUS_IMAGE}
    ports:
      - "${PROMETHEUS_EXTERNAL_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - local-dev-net
    restart: unless-stopped
    deploy:
      replicas: ${BUILD_PROMETHEUS-0}

  grafana:
    container_name: grafana
    image: ${GRAFANA_IMAGE}
    networks:
      - local-dev-net
    ports:
      - "${GRAFANA_EXTERNAL_PORT}:${GRAFANA_PORT}"
    restart: unless-stopped
    depends_on:
      - prometheus
    deploy:
      replicas: ${BUILD_GRAFANA-0}
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning

networks:
  local-dev-net:
    driver: bridge

volumes:
  zookeeper_data:
  zookeeper_datalog:
  kafka_data:
  mysql_data:
  redis_data:
  postgres_data:
  prometheus_data:
  grafana_data:
